services:
  - type: web
    name: drive-log-backend
    env: python
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn eldtracker.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: "3.9"
